const D=window.RDCVillageMapData;
let mapTimer;
function impactCard(v){return [...document.querySelectorAll(".village-summary-card")].find(c=>D.matches(v,c.querySelector("h4")?.textContent))}
function summary(v){const card=impactCard(v);if(!card)return null;const m=[...card.querySelectorAll(".village-metrics span")].map(x=>x.textContent.trim());return{card,text:m.filter(x=>/activit|beneficiar/i.test(x)).join(" · ")}}
function openVillage(v){const s=summary(v);if(s?.card){s.card.click();return}alert(`${v.name} (${v.arabic}) is included in the reference map, but no approved activity summary is currently visible for it.`)}
function setActive(section,name){section.querySelectorAll("[data-village]").forEach(x=>x.classList.toggle("is-active",x.dataset.village===name))}
function bindSvg(root,section){root.querySelectorAll(".village-map-shape[data-village]").forEach(p=>{const v=D.villages.find(x=>x.name===p.dataset.village);const ref=D.references.find(x=>x.name===p.dataset.village);const run=()=>{if(section)setActive(section,p.dataset.village);if(v)openVillage(v);else if(ref)alert(`${ref.name} (${ref.arabic}) is shown as a reference area and is not counted among the 13 villages.`)};p.addEventListener("click",run);p.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();run()}})})}
function card(v){const s=summary(v);return `<button type="button" class="rdc-map-card" data-village="${D.esc(v.name)}" style="--c:${v.color}"><strong>${D.esc(v.name)}</strong><small lang="ar">${D.esc(v.arabic)}</small><span class="rdc-map-state ${s?"has":""}">${D.esc(s?.text||"No approved activity yet")}</span></button>`}
function markup(){return `<article class="panel rdc-village-map-section"><header class="rdc-map-head"><div><h2>13 Villages Geographic Reference</h2><p>Interactive boundaries traced from the uploaded RDC reference map. Select a polygon or village card to open available impact records.</p></div><button type="button" class="rdc-map-open">Open full map</button></header><div class="rdc-map-layout"><div class="rdc-map-canvas">${D.svg()}</div><aside class="rdc-map-side"><h3>Map reference</h3><div class="rdc-map-facts"><div class="rdc-map-fact"><strong>13</strong><span>Official villages</span></div><div class="rdc-map-fact"><strong>0–3 km</strong><span>Displayed scale</span></div><div class="rdc-map-fact"><strong>31°36′–42′E</strong><span>Longitude grid</span></div><div class="rdc-map-fact"><strong>30°24′–26′N</strong><span>Latitude grid</span></div></div><div class="rdc-map-note"><strong>Accuracy:</strong> polygon geometry and relative positions were traced directly from the uploaded map. This is an RDC program reference, not a cadastral or legal survey.</div><h3>Reference features</h3><div class="rdc-map-refs">${D.references.map(r=>`<div class="rdc-map-ref"><span class="rdc-map-swatch" style="background:${r.color}"></span>${D.esc(r.name)} · <span lang="ar" dir="rtl">${D.esc(r.arabic)}</span></div>`).join("")}<div class="rdc-map-ref"><span class="rdc-map-swatch" style="background:#90d8f0"></span>Ismailia Canal · <span lang="ar" dir="rtl">ترعة الإسماعيلية</span></div></div><div class="rdc-map-note"><strong>Source:</strong> ${D.source}</div></aside></div><section class="rdc-map-dir"><div class="rdc-map-dir-head"><div><h3>Village directory</h3><p>All 13 villages remain visible even when no activity has been approved yet.</p></div><input class="rdc-map-search" type="search" placeholder="Search village name"></div><div class="rdc-map-cards">${D.villages.map(card).join("")}</div></section></article>`}
function openFull(){let d=document.querySelector(".rdc-map-dialog");if(!d){d=document.createElement("dialog");d.className="rdc-map-dialog";d.innerHTML=`<div class="rdc-map-dialog-head"><h2>13 Villages Reference Map</h2><button class="rdc-map-dialog-close">×</button></div><div class="rdc-map-dialog-body"></div>`;document.body.appendChild(d);d.querySelector(".rdc-map-dialog-close").onclick=()=>d.close()}d.querySelector(".rdc-map-dialog-body").innerHTML=D.svg();bindSvg(d,null);d.showModal()}
function install(){const anchor=document.querySelector(".village-overview");if(!anchor||document.querySelector(".rdc-village-map-section"))return;const box=document.createElement("div");box.innerHTML=markup();const section=box.firstElementChild;anchor.before(section);section.querySelector(".rdc-map-open").onclick=openFull;bindSvg(section,section);section.querySelectorAll(".rdc-map-card").forEach(c=>{const v=D.villages.find(x=>x.name===c.dataset.village);c.onclick=()=>openVillage(v);c.onmouseenter=c.onfocus=()=>setActive(section,c.dataset.village);c.onmouseleave=c.onblur=()=>setActive(section,"")});section.querySelector(".rdc-map-search").oninput=e=>{const q=D.norm(e.target.value);section.querySelectorAll(".rdc-map-card").forEach(c=>{const v=D.villages.find(x=>x.name===c.dataset.village);c.hidden=!!q&&!v.aliases.some(a=>D.norm(a).includes(q))&&!D.norm(v.arabic).includes(q)})}}
function schedule(){clearTimeout(mapTimer);mapTimer=setTimeout(install,120)}
function start(){schedule();new MutationObserver(schedule).observe(document.getElementById("root")||document.body,{childList:true,subtree:true})}
document.readyState==="loading"?document.addEventListener("DOMContentLoaded",start):start();